#!/usr/bin/env just --justfile

set dotenv-load := true

default:
  just --list

lint:
  pre-commit run ruff -a

setup: && sync-dependencies
  uv venv --prompt {{cookiecutter.virtualenv_name}}
  uv sync


sync-dependencies:
  uv sync

{% raw %}
upgrade-dep dependency:
  uv upgrade {{dependency}}
{% endraw %}

kind := 'report'

coverage kind=kind:
  coverage run -m pytest tests
  coverage kind
