#!/usr/bin/env just --justfile

set dotenv-load := true

default:
  just --list

lint:
  pre-commit run ruff -a

bootstrap: && sync-dependencies pre-commit-install
  uv venv --prompt {{cookiecutter.virtualenv_prompt}}
  uv sync

pre-commit-install:
  uv run pre-commit install

sync-dependencies:
  uv sync

{% raw %}
upgrade-dep dependency:
  uv upgrade {{dependency}}
{% endraw %}

kind := 'report'

coverage kind=kind:
  coverage run -m pytest tests
  coverage kind
