fix = true

[lint]
select = ['ALL']

ignore = ["D211", 'D212',  'COM812', 'ISC001', 'Q003','Q000', 'Q', 'D', 'C408', 'ANN', 'FA', 'PERF203']

# 3. Avoid trying to fix flake8-bugbear ('B') violations.
unfixable = ["B"]


[lint.per-file-ignores]
# Ignore 'E402' (import violations) in all '__init__.py' files, and in select subdirectories.
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402", 'E501', 'S101']

[format]
quote-style = "single"
